apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spinharmony-studio
  title: spinharmony-studio
  description: A graphical user interface for the spinharmony package, for analysing magnetic diffuse scattering data
spec:
  type: application
  lifecycle: experimental
  owner: group:default/data-analysis
